### ISSUE TITLE
ResourceNotFoundException

### ISSUE THREAD

**Issue by joekendal** [awslabs/fhir-works-on-aws-deployment#216]
Having followed the steps in DEVELOPMENT.md, when running `serverless offline` and trying a `POST` request, I am greeted with the following exception:

```
ResourceNotFoundException: Requested resource not found
    at Request.extractError (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/event_listeners.js:313:13)
    at IncomingMessage.emit (node:events:388:22)
    at IncomingMessage.EventEmitter.emit (node:domain:470:12)
    at endReadableNT (node:internal/streams/readable:1295:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  code: 'ResourceNotFoundException',
  time: 2021-02-20T21:56:49.652Z,
  requestId: 'M172QB2R4NG010Q0BAQCNV7RUJVV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
  retryDelay: 0.6577762230455808
}
Unhandled Error ResourceNotFoundException: Requested resource not found
    at Request.extractError (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/Users/joe/Dev/fhir-works/fhir-works-on-aws-persistence-ddb/node_modules/aws-sdk/lib/event_listeners.js:313:13)
    at IncomingMessage.emit (node:events:388:22)
    at IncomingMessage.EventEmitter.emit (node:domain:470:12)
    at endReadableNT (node:internal/streams/readable:1295:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  code: 'ResourceNotFoundException',
  time: 2021-02-20T21:56:49.652Z,
  requestId: 'M172QB2R4NG010Q0BAQCNV7RUJVV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
  retryDelay: 0.6577762230455808
}
```

These packages are definitely installed...

**Comment by shengc5** [comment]
@joekendal can you share what was the cause of the issue above? Thanks!
