### ISSUE TITLE
IncompleteSignatureException: not a valid key=value pair (missing equal-sign) in Authorization header

### ISSUE THREAD

**Issue by robertlario** [awslabs/fhir-works-on-aws-deployment#379]
Can you provide me with any insight on what might lead to this exception?  It certainly feels like a security issue, but I have checked all the parameters and keys.

I am debugging the lambda locally, calling out to dynamodb running on AWS.

Thoughts?

```
arg0: IncompleteSignatureException: '/20210706/us-east-2/dynamodb/aws4_request' not a valid key=value pair (missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256 Credential=<cred> /20210706/us-east-2/dynamodb/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-target, Signature=f25d654c0543603xxxxxxxa2924ed7fa8365fde8b972231'.
    at Request.extractError (c:\AWS-FHIR\fhir-works-on-aws-deployment\node_modules\aws-sdk\lib\protocol\json.js:52:27)
    at Request.callListeners (c:\AWS-FHIR\fhir-works-on-aws-deployment\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (c:\AWS-FHIR\fhir-works-on-aws-deployment\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (c:\AWS-FHIR\fhir-works-on-aws-deployment\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (c:\AWS-FHIR\fhir-works-on-aws-deployment\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (c:\AWS-FHIR\fhir-works-on-aws-deployment\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at c:\AWS-FHIR\fhir-works-on-aws-deployment\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (c:\AWS-FHIR\fhir-works-on-aws-deployment\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (c:\AWS-FHIR\fhir-works-on-aws-deployment\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (c:\AWS-FHIR\fhir-works-on-aws-deployment\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
    at Request.emit (c:\AWS-FHIR\fhir-works-on-aws-deployment\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (c:\AWS-FHIR\fhir-works-on-aws-deployment\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (c:\AWS-FHIR\fhir-works-on-aws-deployment\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (c:\AWS-FHIR\fhir-works-on-aws-deployment\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at c:\AWS-FHIR\fhir-works-on-aws-deployment\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (c:\AWS-FHIR\fhir-works-on-aws-deployment\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (c:\AWS-FHIR\fhir-works-on-aws-deployment\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (c:\AWS-FHIR\fhir-works-on-aws-deployment\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
    at callNextListener (c:\AWS-FHIR\fhir-works-on-aws-deployment\node_modules\aws-sdk\lib\sequential_executor.js:96:12)
    at IncomingMessage.onEnd (c:\AWS-FHIR\fhir-works-on-aws-deployment\node_modules\aws-sdk\lib\event_listeners.js:336:13)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {message: ''/20210706/us-east-2/dynamodb/aws4_request' …244289e1xxx365fde8b972231'.', code: 'IncompleteSignatureException', time: Tue Jul 06 2021 10:42:24 GMT-0400 (Eastern Daylight Time), requestId: '6DHVJxxxxxxQ9ASUAAJG', statusCode: 400, …}
```

**Comment by rsmayda** [comment]
To get a better understanding of this; can you explain your set-up?
- Do you have FHIR Works on AWS deployed?
- Are you running `sls deploy`?
- Are you using `yalc` to have a local `persistence` deployed?
- Any other pertinent information?

**Comment by robertlario** [comment]
I just reset the entire environment.  I do not know what caused the issue, but it's working fine now.  Thx
