### ISSUE TITLE
[Bug] FHIR Works on AWS UI deployment failed

### ISSUE THREAD

**Issue by imadeit** [awslabs/fhir-works-on-aws-deployment#565]
**Describe the bug**
When I tried to deploy the FWoA UI after deploying FWoA backend using the instructions below, the deployment failed due to the error shown below.
https://github.com/awslabs/fhir-works-on-aws-ui/tree/mainline/amplify-infra

**To Reproduce**
Run the proposed command as below:
$ cd fhir-works-on-aws-ui/amplify-infra
$ yarn run cdk deploy -c fhir_server_url="<REACT_APP_FHIR_SERVER_URL>" -c auth_url="<REACT_APP_AUTH_URL>" -c client_id="<REACT_APP_CLIENT_ID>" -c api_key="<REACT_APP_API_KEY>" [-c amplify_branch="<BRANCH>"]
yarn run v1.22.17

**Expected behavior**
Build and deploy the project

**Screenshots**
Some error logs: (some information masked)
yarn run v1.22.17
$ cdk deploy -c fhir_server_url=https://xxx.execute-api.us-west-2.amazonaws.com/dev -c auth_url=https://yyy.auth.us-west-2.amazoncognito.com -c client_id=yyy -c api_key=zzz

/Users/user/FWoA/fhir-works-on-aws-ui/amplify-infra/node_modules/@aws-cdk/aws-iam/lib/principals.ts:540
    return stack.regionalFact(
                 ^
TypeError: Resolution error: Resolution error: Resolution error: Resolution error: stack.regionalFact is not a function.
Object creation stack:
  at stack traces disabled.
Object creation stack:
  at stack traces disabled..
    at ServicePrincipalToken.resolve (/Users/user/FWoA/fhir-works-on-aws-ui/amplify-infra/node_modules/@aws-cdk/aws-iam/lib/principals.ts:540:18)
    at RememberingTokenResolver.resolveToken (/Users/user/FWoA/fhir-works-on-aws-ui/amplify-infra/node_modules/@aws-cdk/core/lib/resolvable.ts:147:24)
    at RememberingTokenResolver.resolveToken (/Users/user/FWoA/fhir-works-on-aws-ui/amplify-infra/node_modules/@aws-cdk/core/lib/private/resolve.ts:273:18)
    at resolve (/Users/user/FWoA/fhir-works-on-aws-ui/amplify-infra/node_modules/@aws-cdk/core/lib/private/resolve.ts:202:51)
    at Object.resolve [as mapToken] (/Users/user/FWoA/fhir-works-on-aws-ui/amplify-infra/node_modules/@aws-cdk/core/lib/private/resolve.ts:112:77)
    at TokenizedStringFragments.mapTokens (/Users/user/FWoA/fhir-works-on-aws-ui/amplify-infra/node_modules/@aws-cdk/core/lib/string-fragments.ts:71:33)
    at RememberingTokenResolver.resolveString (/Users/user/FWoA/fhir-works-on-aws-ui/amplify-infra/node_modules/@aws-cdk/core/lib/resolvable.ts:168:22)
    at RememberingTokenResolver.resolveString (/Users/user/FWoA/fhir-works-on-aws-ui/amplify-infra/node_modules/@aws-cdk/core/lib/private/resolve.ts:277:23)
    at resolve (/Users/user/FWoA/fhir-works-on-aws-ui/amplify-infra/node_modules/@aws-cdk/core/lib/private/resolve.ts:160:48)
    at Object.resolve (/Users/user/FWoA/fhir-works-on-aws-ui/amplify-infra/node_modules/@aws-cdk/core/lib/private/resolve.ts:112:77)
Subprocess exited with error 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Versions (please complete the following information):**
 - Release Version installed or commit hash [e.g. v1.0.3, 1edf4]
node: v16.3.0

**Additional context**
https://github.com/aws/aws-cdk/issues/18252
According to the issue above, it seems it is the CDK's version's problem.
By changing the dependency to 1.137.0, it worked.

**Comment by nguyen102** [comment]
Hi @imadeit, thanks for filing this bug and helping us fix it. For correct bug tracking, can you please file this Bug in the [UI repo](https://github.com/awslabs/fhir-works-on-aws-ui/issues)?

Thank you!

**Comment by imadeit** [comment]
Hi @nguyen102 , sorry for creating to the wrong place.
Actually I tried to fix the issue and proposed a pull request shown above.
Thanks!
