### ISSUE TITLE
[Bug] compile script is not work while Installing IG

### ISSUE THREAD

**Issue by ughvj** [awslabs/fhir-works-on-aws-deployment#604]
Hi everyone.

I'm installing IG with referring [this guide](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/USING_IMPLEMENTATION_GUIDES.md).
Then, I faced with a problem below at step3.

```
$ pwd
/<project_dir>/fhir-works-on-aws-deployment
$ npm install
<omitted>
$ yarn run compile-igs
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/errors' is not defined by "exports" in /<project_dir>/node_modules/@elastic/elasticsearch/package.json
    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:448:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:727:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/<project_dir>/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by ssvegaraju** [comment]
Hi @ughvj, thank you for bringing up this issue. Could I ask what version of node and the deployment package you are using? And also what IGs you are trying to deploy, if possible? We use yarn as our package manager, so you could try deleting the `package-lock.json` and `node_modules` folder, and reinstall using `yarn install` rather than `npm install`.

**Comment by ughvj** [comment]
Hi @ssvegaraju , Thank you very much for your reply. 

1. informations of each package is below.

```
 $ node --version
v17.8.0
 $ npm --version
8.5.5
 $ yarn --version
1.22.17
```

2. I'm trying to deploy [JP Core](https://registry.fhir.org/package/JP-CORE.Draft%7C1.0.5) as IG.

3. Re-run complie script with deleting directories of node-related. result is below.

```
 $ pwd
/<project_dir>/fhir-works-on-aws-deployment
 $ rm -rf node_modules
 $ rm -rf package-lock.json
 $ yarn install
yarn install v1.22.17
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning Resolution field "http-errors@1.8.0" is incompatible with requested version "http-errors@1.7.2"
warning Resolution field "http-errors@1.8.0" is incompatible with requested version "http-errors@~1.7.2"
warning Resolution field "http-errors@1.8.0" is incompatible with requested version "http-errors@1.7.2"
[3/5] 🚚  Fetching packages...
error concat-text-webpack-plugin@0.1.10: The engine "node" is incompatible with this module. Expected version ">=8 <=16". Got "17.8.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by ughvj** [comment]
Hi @ssvegaraju , thank you very much for your reply.

It works with deleting node-related directories! description is below.

```
 $ node --version
v17.8.0
 $ npm --version
8.5.5
 $ yarn --version
1.22.17
 $ pwd
/<project_dir>/fhir-works-on-aws-deployment
 $ rm -rf package-lock.json
 $ rm -rf node_modules
 $ yarn install
yarn install v1.22.17
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning Resolution field "http-errors@1.8.0" is incompatible with requested version "http-errors@1.7.2"
warning Resolution field "http-errors@1.8.0" is incompatible with requested version "http-errors@~1.7.2"
warning Resolution field "http-errors@1.8.0" is incompatible with requested version "http-errors@1.7.2"
[3/5] 🚚  Fetching packages...
error concat-text-webpack-plugin@0.1.10: The engine "node" is incompatible with this module. Expected version ">=8 <=16". Got "17.8.0"
error Found incompatible module.
info Visit <https://yarnpkg.com/en/docs/cli/install> for documentation about this command.
 $ sudo n 15.14.0 // downgrade
 $ node --version
v15.14.0
 $ yarn install
<omitted>
success Saved lockfile.
✨  Done in 27.09s.
$ yarn run compile-igs
yarn run v1.22.17
$ ts-node scripts/compile-igs.ts
looking at ig path: /Users/ugh/repo/fhir-works-on-aws-deployment/implementationGuides/JP-CORE.Draft
checking /Users/ugh/repo/fhir-works-on-aws-deployment/implementationGuides/JP-CORE.Draft/package.json
Exception:  '.index.json' not found in /Users/ugh/repo/fhir-works-on-aws-deployment/implementationGuides/JP-CORE.Draft Error: '.index.json' not found in /Users/ugh/repo/fhir-works-on-aws-deployment/implementationGuides/JP-CORE.Draft
    at IGCompiler.collectResources (/Users/ugh/repo/fhir-works-on-aws-deployment/src/implementationGuides/IGCompiler.ts:77:19)
    at IGCompiler.compileIGs (/Users/ugh/repo/fhir-works-on-aws-deployment/src/implementationGuides/IGCompiler.ts:108:46)
    at async compileIGs (/Users/ugh/repo/fhir-works-on-aws-deployment/scripts/compile-igs.ts:46:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Then, I trying to deploy [JP Core](https://registry.fhir.org/package/JP-CORE.Draft%7C1.0.5). But it don't include `.index.json`  and don't work IGCompiler. Should I create `.index.json` manually?

**Comment by ssvegaraju** [comment]
Yes, our IG Compiler requires an `.index.json` to parse an implementation guide. A good example of one can be found included in the [r4 core IG](https://registry.fhir.org/package/hl7.fhir.r4.core|4.0.1). They are pretty simple to construct in the case that an IG doesn't come with one. Please let us know if this still doesn't resolve your issue!

**Comment by ughvj** [comment]
@ssvegaraju Thank you for your prompt reply. I really appreciate your time and effort!

**Comment by ssvegaraju** [comment]
Anytime! Feel free to reopen if there are any further questions.

**Comment by ughvj** [comment]
I'm sorry for reopening this issue.

Where should I locate outputs of IGCompiler?
Now, It is in below.

```
 $ pwd
/<project_dir>/fhir-works-on-aws-deployment
 $ ls -la
<omitted>
-rw-r--r--   1 ugh  staff  24185  4  4 16:52 fhir-works-on-aws-routing.json
-rw-r--r--   1 ugh  staff  36210  4  4 16:52 fhir-works-on-aws-search-es.json
<omitted>
```

I implemented step4 and step5 , but  I'm not sure it's installed completely.

**Comment by ssvegaraju** [comment]
Hey! The output of the `yarn run compile-igs` step will be output to a directory `compiledImplementationGuides`. This assumes that the implementation guides you wish to compile are placed in the `implementationGuides` folder. One way to check if the implementation guides are present is to get the [Capability Statement](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/USING_IMPLEMENTATION_GUIDES.md#capability-statement) after you've deployed successfully and search for your IG.

**Comment by ughvj** [comment]
@ssvegaraju 
JPCore worked finally! `Capability Statement` includes attributes of JPCore-related.
thank you very very much!
