### ISSUE TITLE
[Bug] Cannot read property 'split' of undefined in FHIR server

### ISSUE THREAD

**Issue by alex-harvey-z3q** [awslabs/fhir-works-on-aws-deployment#685]
# Description

When building v5.0.0 of the FHIR server:

## To reproduce

* Mac OS X (Monterey)
* Node v14.20.0
* Serverless
```
Framework Core: 3.22.0
Plugin: 6.2.2
SDK: 4.3.2
```

1. Clone latest version of this project
2. Git checkout v5.0.0
3. Changes to serverless.yaml:
```diff
% git diff v5.0.0 serverless.yaml 
diff --git a/serverless.yaml b/serverless.yaml
index 6e3dbb0..485543c 100644
--- a/serverless.yaml
+++ b/serverless.yaml
@@ -14,7 +14,7 @@ custom:
   region: ${opt:region, self:provider.region}
   oauthRedirect: ${opt:oauthRedirect, 'http://localhost'}
   config: ${file(serverless_config.json)}
-  useHapiValidator: ${opt:useHapiValidator, 'false'}
+  useHapiValidator: 'true'
   enableMultiTenancy: ${opt:enableMultiTenancy, 'false'}
   enableSubscriptions: ${opt:enableSubscriptions, 'false'}
   logLevel: ${opt:logLevel, 'error'}
@@ -38,7 +38,7 @@ custom:
 
 provider:
   name: aws
-  region: us-west-2
+  region: ap-southeast-2
   stage: dev
   runtime: nodejs14.x
   architecture: x86_64
@@ -110,7 +110,7 @@ functions:
           method: GET
           path: /tenant/{tenantId}/metadata
     handler: src/index.handler
-    provisionedConcurrency: 5
+      #provisionedConcurrency: 5
     environment:
       EXPORT_STATE_MACHINE_ARN: !Ref BulkExportStateMachine
       PATIENT_COMPARTMENT_V3: ${self:custom.patientCompartmentFileV3}
```

4. Changes to HAPI validator directory:

```diff
diff --git a/javaHapiValidatorLambda/pom.xml b/javaHapiValidatorLambda/pom.xml
index 2875078..fbb4875 100644
--- a/javaHapiValidatorLambda/pom.xml
+++ b/javaHapiValidatorLambda/pom.xml
@@ -29,6 +29,7 @@
         <!--The following runtime dependencies are specific to a FHIR version-->
         <!--Enable the dependencies for the FHIR version that you want to support -->
         <!-- ============ Dependencies for FHIR R4 ============ -->
+<!--
         <dependency>
             <groupId>ca.uhn.hapi.fhir</groupId>
             <artifactId>hapi-fhir-validation-resources-r4</artifactId>
@@ -43,20 +44,18 @@
             <groupId>ca.uhn.hapi.fhir</groupId>
             <artifactId>hapi-fhir-validation-resources-dstu3</artifactId>
             <version>5.3.0</version>
-            <!--Note that the scope is test-->
             <scope>test</scope>
         </dependency>
         <dependency>
             <groupId>ca.uhn.hapi.fhir</groupId>
             <artifactId>hapi-fhir-structures-dstu3</artifactId>
             <version>5.3.0</version>
-            <!--Note that the scope is test-->
             <scope>test</scope>
         </dependency>
+-->
         <!-- ================================================== -->
 
         <!-- ============ Dependencies for FHIR DSTU3 ============ -->
-<!--
         <dependency>
             <groupId>ca.uhn.hapi.fhir</groupId>
             <artifactId>hapi-fhir-validation-resources-dstu3</artifactId>
@@ -79,7 +78,6 @@
             <version>5.3.0</version>
             <scope>test</scope>
         </dependency>
--->
         <!-- ================================================== -->
 
         <dependency>
@@ -155,7 +153,7 @@
         <dependency>
             <groupId>org.projectlombok</groupId>
             <artifactId>lombok</artifactId>
-            <version>1.18.16</version>
+            <version>1.18.22</version>
             <scope>provided</scope>
         </dependency>
         <dependency>
diff --git a/javaHapiValidatorLambda/serverless.yml b/javaHapiValidatorLambda/serverless.yml
index 1f4fae9..543e94e 100644
--- a/javaHapiValidatorLambda/serverless.yml
+++ b/javaHapiValidatorLambda/serverless.yml
@@ -7,12 +7,12 @@ service: fhir-service-validator
 
 custom:
   stage: ${opt:stage, self:provider.stage}
-  fhirVersion: ${opt:fhirVersion, '4.0.1'}
+  fhirVersion: '3.0.1'
   region: ${opt:region, self:provider.region}
 
 provider:
   name: aws
-  region: us-west-2
+  region: ap-southeast-2
   stage: dev
   runtime: java11
   logRetentionInDays: 3653 # 10 years
@@ -47,7 +47,7 @@ resources:
         AllowedValues:
           - '4.0.1'
           - '3.0.1'
-        Description: 'The FHIR version used by the validator. Default: 4.0.1'
+        Description: 'The FHIR version used by the validator. Default: 3.0.1'
   - Outputs:
       ValidatorLambdaAlias:
         Description: Validator lambda function alias
```

5. Install using this Makefile code

```make
_validator_package:  ## Build the HAPI validator
  (cd javaHapiValidatorLambda && mvn package)

_validator_deploy:  ## Deploy the HAPI validator stack
  (cd javaHapiValidatorLambda && serverless deploy -s $(STAGE) -r ap-southeast-2)

validator: _is_set_stage _validator_package _validator_deploy  ## Build and deploy the HAPI validator stack

_step_functions:
  serverless plugin install -n serverless-step-functions

install: _is_set_stage _step_functions  ## Build and deploy the FHIR service stack
  serverless deploy -s $(STAGE) -r ap-southeast-2
```

```
STAGE=dev make install
```

**Expected behavior**
A working FHIR server

**Actual behavior**

FHIR Server CloudWatch logs:

```json
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'split' of undefined",
    "stack": [
        "TypeError: Cannot read property 'split' of undefined",
        "    at toIdentifier (/var/task/src/webpack:/Users/alexharvey/git/fhir-works-on-aws-deployment/node_modules/toidentifier/index.js:24:1)",
        "    at forEachCode (/var/task/src/webpack:/Users/alexharvey/git/fhir-works-on-aws-deployment/node_modules/http-errors/index.js:267:1)",
        "    at Array.forEach (<anonymous>)",
        "    at populateConstructorExports (/var/task/src/webpack:/Users/alexharvey/git/fhir-works-on-aws-deployment/node_modules/http-errors/index.js:265:1)",
        "    at Object.<anonymous> (/var/task/src/webpack:/Users/alexharvey/git/fhir-works-on-aws-deployment/node_modules/http-errors/index.js:31:1)",
        "    at __webpack_require__ (/var/task/src/webpack:/webpack/bootstrap:19:1)",
        "    at Object.<anonymous> (/var/task/src/webpack:/Users/alexharvey/git/fhir-works-on-aws-deployment/node_modules/send/index.js:15:19)",
        "    at __webpack_require__ (/var/task/src/webpack:/webpack/bootstrap:19:1)",
        "    at Object.<anonymous> (/var/task/src/webpack:/Users/alexharvey/git/fhir-works-on-aws-deployment/node_modules/express/lib/utils.js:20:12)",
        "    at __webpack_require__ (/var/task/src/webpack:/webpack/bootstrap:19:1)"
    ]
}
```

## Root cause analysis

I found that a broken version of the send NPM module is being installed as a dependency of `express`.

## Work around

I manually copied over the top of it the latest send module from master and rebuild the Lambda zip file, and that fixed it:

```diff
--- bad 2022-09-05 01:29:57.000000000 +1000
+++ good        2022-09-05 01:29:25.000000000 +1000
@@ -1,7 +1,7 @@
 function populateConstructorExports (exports, codes, HttpError) {
   codes.forEach(function forEachCode (code) {
     var CodeError
-    var name = toIdentifier(statuses[code])
+    var name = toIdentifier(statuses.message[code])
 
     switch (codeClass(code)) {
       case 400:
@@ -18,8 +18,4 @@
       exports[name] = CodeError
     }
   })
-
-  // backwards-compatibility
-  exports["I'mateapot"] = deprecate.function(exports.ImATeapot,
-    '"I\'mateapot"; use "ImATeapot" instead')
 }
```

**Comment by FernandoAranda** [comment]
Hi @alexharv074 ,  thanks for bringing up this issue! , I've added this to our team's backlog, and we'll update here when we have more information.
-Fernando

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
